### PR TITLE
def fun to fix IntendedFor field in fmap phase1 and phase2

### PR DESCRIPTION
**Pull request by giulia-berto**
fixing IntendedFor field for phase1.json and phase2.json by writing the fmri path in it

### CODE REVIEW

**Comment by soichih** [comment]
Thanks for the PR @giulia-berto I have a couple of thoughts.

1) fmri_path is set during the same loop as it's updating the json. There is no guarantee that the bold data will be stored before fmap. So it might not be set when fmap is handled. I think one way to solve this is to first go through all input and look for which fmap should be mapped to which bold/dwi, then write out the updated json on the existing loop.

2) You are first symbolic linking the src json to dest, then updating the json through the filename given by the dest. This probably won't work as the input data is read-only on brainlife. You won't be able to update it through symlink. I also find this a bit round-about.

```
                if src.endswith("phase1.json"):
                    link(src, dest+"_phase1.json")
                    fixIntendedFor(dest+"_phase1.json", fmri_path)
```

Instead, you could just update the fixIntendedFor to have both src and dest path, as well as any sidecar content that you'd like to override.. For example, if could look like this instead.

```
                if src.endswith("phase1.json"):
                    copyJSON(src, dest+"_phase1.json", override={"IntendedFor": fmri_path})
```

Then the copyJSON function will do the following
1) Read the json file specified in the src path.
2) Apply any override specified
3) Write out the new json on the specified dest path.

**Comment by soichih** [comment]
3) Is there a reason the IntendedFor fixes are only applied to phase1/2? I think all fmap json needs to be updated.

4) @dlevitas mentioned that fmap can also apply to dwi data. I don't think we have instance of this in brainlife right now, but just FYI.

**Comment by dlevitas** [comment]
This [post](https://neurostars.org/t/bids-b0-correction-for-dwi/3802) gives an example of field maps meant for DWI acquisitions

**Comment by giulia-berto** [comment]
@soichih I updated the PR:
* the fixIntendedFor function was replaced by the copyJSON function as you suggested
* the first for loop over inputs retrieves the intended paths (dwi and/or fmri)
* a second for loop over inputs fixes the IntendedFor field for all fmap json files
That was needed to avoid rewriting the code to retrieve `path` and `name`. I think it would be better to have functions like getPath and getName (like getModality). 
Also, can we make the script more verbose?

**Comment by soichih** [comment]
Thank you @giulia-berto I've merged the PR. I will test it and release it to our various resources once I confirm that it works properly.

**Pull request merged**
