### PR TITLE
replace desc-<id> with run-<id>

### PR DESCRIPTION
**Pull request by giulia-berto**

### CODE REVIEW

**Comment by soichih** [comment]
@giulia-berto Thanks. I've merged it. Can you also do the following?

For dwi, please set the following entities if it's available in the metadata.

```
acq
dir 
run
part
```
For anat

```
run
acq
ce
rec
part
```

For fmap

```
acq
run
```

For func

```
task (already set?)
acq
ce
rec
dir
run
echo
part
```

For eeg

```
task
acq
run
```

For meg

```
task
acq
run
proc
split
```

If the metadata has "run" already, it should use the value from the meta instead of auto-generated sequence number. Also, maybe we should only set "run" if there are multiple objects with the identical entities?

**Comment by giulia-berto** [comment]
Yes, if metadata has already "run", it uses that value. I don't think that appending run-<id> to every object is harmful, is it? Ok, I'll add the missing entities.

**Comment by soichih** [comment]
A lot of BIDS Apps use BIDS entities (including run-) as part of output file names, report names, etc. so I think we should avoid adding any BIDS entities unless necessary?

**Comment by guiomar** [comment]
I think `task` could be less prone to error. Runs of the same task might be grouped together by some analysis pipelines. Usually files from different tasks are taken separately

**Comment by soichih** [comment]
I see.. but run-/acq- are the only entities that are supported across all modalities, so I think we should stick with the same entity (run?) to disambiguate BIDS file paths that are colliding. 

But again, I think we should focus on setting all entities available from metadata, and if that's not enough to keep all files separate, then we should probably raise a warning to the user that we are resorting to do some weird manipulation of bids entities to make things separate.

**Pull request merged**
