### PR TITLE
adding convert PhaseEncodingDirection from xyz to ijk convention

### PR DESCRIPTION
**Pull request by giulia-berto**

### CODE REVIEW

**Comment by soichih** [comment]
Thanks @giulia-berto!

Is it possible to add a check so that the image is in LAS when we do this conversion? If not, we need to apply different mappings, probably see https://github.com/nipreps/fmriprep/issues/2341#issuecomment-737431340

Also, please add some warning messages that we are doing this conversion.. I think the user should know about it?

**Comment by giulia-berto** [comment]
I thought about it, but I couldn't find the orientation in the config.json file...should we read it from the nii files?

There's already the `print("convert PhaseEncodingDirection from xyz to ijk convention")` if that's what you mean.

**Comment by soichih** [comment]
I think we can do something like this

**Comment by giulia-berto** [comment]
I made an update. I think we should check for "any *A* orientation" as effigies said, so `if 'A' in codes`. 

Another problem is from which image we should read such orientation? The t1 might not be in the dataset.

**Comment by soichih** [comment]
I believe the affine code should come from the .json's corresponding .nii.gz (the. nii.gz of the object itself).

Also, I believe what Chris means is that, if we are converting "y" to "j", then I need to check the second item in the code (P v.s A). If we are converting "x" to "I", then we should check if the first item in the core is L or R. If we are converting "z" to "k", then we should check if the 3rd item in the code is I or S. My example code does that basically.

**Comment by soichih** [comment]
Thanks for the update @giulia-berto I think the code still doesn't properly handle cases where voxels are stored in odd strides like ('A', 'R', 'S'), or ('S', 'A', 'R'), etc.. Chris says that it should be very rare, so maybe we don't need to worry about it, but we need to remember this.

**Comment by giulia-berto** [comment]
Yes, I also think that it's not handling correctly those cases, and I'd have done something like this to flip the polarity:
```
inv = pe[1:] == "-"
if codes[axis] in ('L', 'P', 'I'):
    inv = not inv 
if inv:
    updated_pe += "-" 
```
However it can be that I misunderstood all this flipping thing, so feel free to change that function.

**Pull request merged**
